-- Database Table Structures
-- Generated on: 2025-07-16 15:25:46
-- Database: allstars
-- MySQL Version: 8.0.39

-- Table: case_procedure_codes
CREATE TABLE `case_procedure_codes` (
  `case_id` varchar(100) DEFAULT NULL,
  `procedure_code` varchar(10) DEFAULT NULL,
  KEY `case_id` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: cases
CREATE TABLE `cases` (
  `case_id` varchar(100) NOT NULL,
  `user_id` varchar(100) DEFAULT NULL,
  `case_date` date DEFAULT NULL,
  `patient_first` varchar(250) DEFAULT NULL,
  `patient_last` varchar(250) DEFAULT NULL,
  `ins_provider` varchar(250) DEFAULT NULL,
  `surgeon_id` int DEFAULT NULL,
  `facility_id` int DEFAULT NULL,
  `case_create_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `case_updated_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `case_status` smallint DEFAULT '0' COMMENT '0 = incomplete, 1 = not paid, 2 = pending payment, 3 = paid',
  `paid_to_provider_ts` timestamp NULL DEFAULT NULL,
  `biller_status` smallint DEFAULT '0' COMMENT '0 = None, 1 = Sent to biller, 2 = received payment, 3 = Sent to negotiation, 4 = Negotiation Settled, 5 = Sent to IDR, 6 = IDR decision made, 7 = Closed',
  `sent_to_biller_ts` timestamp NULL DEFAULT NULL,
  `received_pmnt_ts` timestamp NULL DEFAULT NULL,
  `sent_to_negotiation_ts` timestamp NULL DEFAULT NULL,
  `settled_ts` timestamp NULL DEFAULT NULL,
  `sent_to_idr_ts` timestamp NULL DEFAULT NULL,
  `idr_decision_ts` timestamp NULL DEFAULT NULL,
  `closed_ts` timestamp NULL DEFAULT NULL,
  `demo_file` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `note_file` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `misc_file` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `active` tinyint DEFAULT '1',
  `human_case_id` bigint NOT NULL AUTO_INCREMENT,
  `pay_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`case_id`),
  KEY `user_id` (`user_id`),
  KEY `human_case_id` (`human_case_id`),
  KEY `idx_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: cpt_codes
CREATE TABLE `cpt_codes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `cpt_cat` varchar(20) DEFAULT NULL,
  `cpt_code` varchar(10) DEFAULT NULL,
  `cpt_description` varchar(2500) DEFAULT NULL,
  `code_status` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1164 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: deleted_case_procedure_codes
CREATE TABLE `deleted_case_procedure_codes` (
  `case_id` varchar(100) DEFAULT NULL,
  `procedure_code` varchar(10) DEFAULT NULL,
  KEY `case_id` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: deleted_cases
CREATE TABLE `deleted_cases` (
  `case_id` varchar(100) NOT NULL,
  `user_id` varchar(100) DEFAULT NULL,
  `case_date` date DEFAULT NULL,
  `patient_first` varchar(250) DEFAULT NULL,
  `patient_last` varchar(250) DEFAULT NULL,
  `ins_provider` varchar(250) DEFAULT NULL,
  `surgeon_id` int DEFAULT NULL,
  `facility_id` int DEFAULT NULL,
  `case_create_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `case_updated_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `case_status` smallint DEFAULT '0' COMMENT '0 = incomplete, 1 = not paid, 2 = pending payment, 3 = paid',
  `paid_to_provider_ts` timestamp NULL DEFAULT NULL,
  `biller_status` smallint DEFAULT '0' COMMENT '0 = None, 1 = Sent to biller, 2 = received payment, 3 = Sent to negotiation, 4 = Negotiation Settled, 5 = Sent to IDR, 6 = IDR decision made, 7 = Closed',
  `sent_to_biller_ts` timestamp NULL DEFAULT NULL,
  `received_pmnt_ts` timestamp NULL DEFAULT NULL,
  `sent_to_negotiation_ts` timestamp NULL DEFAULT NULL,
  `settled_ts` timestamp NULL DEFAULT NULL,
  `sent_to_idr_ts` timestamp NULL DEFAULT NULL,
  `idr_decision_ts` timestamp NULL DEFAULT NULL,
  `closed_ts` timestamp NULL DEFAULT NULL,
  `demo_file` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `note_file` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `misc_file` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `active` tinyint DEFAULT '1',
  `human_case_id` bigint NOT NULL AUTO_INCREMENT,
  `pay_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`case_id`),
  KEY `user_id` (`user_id`),
  KEY `human_case_id` (`human_case_id`),
  KEY `idx_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: deleted_facilities
CREATE TABLE `deleted_facilities` (
  `facility_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` varchar(100) DEFAULT NULL,
  `facility_name` varchar(1000) DEFAULT NULL,
  `facility_npi` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`facility_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: deleted_surgeons
CREATE TABLE `deleted_surgeons` (
  `surgeon_id` int NOT NULL AUTO_INCREMENT,
  `user_id` varchar(100) DEFAULT NULL,
  `first_name` varchar(250) DEFAULT NULL,
  `last_name` varchar(250) DEFAULT NULL,
  `surgeon_npi` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`surgeon_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: deleted_user_documents
CREATE TABLE `deleted_user_documents` (
  `user_id` varchar(100) DEFAULT NULL,
  `document_type` varchar(100) DEFAULT NULL,
  `document_name` varchar(250) DEFAULT NULL,
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: deleted_users
CREATE TABLE `deleted_users` (
  `user_id` varchar(100) NOT NULL,
  `user_email` varchar(250) NOT NULL,
  `first_name` varchar(250) DEFAULT NULL,
  `last_name` varchar(250) DEFAULT NULL,
  `addr1` varchar(250) DEFAULT NULL,
  `addr2` varchar(250) DEFAULT NULL,
  `city` varchar(250) DEFAULT NULL,
  `state` varchar(250) DEFAULT NULL,
  `zipcode` varchar(250) DEFAULT NULL,
  `telephone` bigint unsigned DEFAULT NULL,
  `user_npi` bigint unsigned DEFAULT NULL COMMENT 'National Provider Identification',
  `referred_by_user` varchar(100) DEFAULT NULL,
  `user_type` int unsigned DEFAULT '1' COMMENT '1 = Provider, 2 = Group Admin, 10 = Case Admin, 20 = User Admin, 100 = Global Admin, 999 = System Admin',
  `message_pref` smallint DEFAULT '0' COMMENT '0 = no messages, 1 = email, 2 = sms, 3 = both',
  `create_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login_dt` datetime DEFAULT NULL,
  `active` tinyint DEFAULT '1',
  `states_licensed` varchar(500) DEFAULT NULL,
  `last_updated_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_tier` int unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`user_id`),
  KEY `idx_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: doc_type_list
CREATE TABLE `doc_type_list` (
  `doc_type` varchar(200) NOT NULL,
  PRIMARY KEY (`doc_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: facility_list
CREATE TABLE `facility_list` (
  `facility_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` varchar(100) DEFAULT NULL,
  `facility_name` varchar(1000) DEFAULT NULL,
  `facility_npi` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`facility_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000033 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: group_list
CREATE TABLE `group_list` (
  `group_id` int NOT NULL AUTO_INCREMENT,
  `group_desc` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: groups
CREATE TABLE `groups` (
  `group_id` int NOT NULL AUTO_INCREMENT,
  `group_desc` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: name_table
CREATE TABLE `name_table` (
  `provider_last_name` varchar(35) DEFAULT NULL,
  `provider_first_name` varchar(20) DEFAULT NULL,
  `recs` bigint NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: npi_data
CREATE TABLE `npi_data` (
  `npi` bigint DEFAULT NULL,
  `entity_type_code` varchar(1) DEFAULT NULL,
  `employer_identification_number` varchar(9) DEFAULT NULL,
  `provider_organization_name` text,
  `provider_last_name` text,
  `provider_first_name` varchar(20) DEFAULT NULL,
  `provider_middle_name` varchar(20) DEFAULT NULL,
  `provider_name_prefix_text` varchar(5) DEFAULT NULL,
  `provider_name_suffix_text` varchar(4) DEFAULT NULL,
  `provider_credential_text` varchar(20) DEFAULT NULL,
  `provider_other_organization_name` varchar(9) DEFAULT NULL,
  `provider_other_organization_name_type_code` varchar(1) DEFAULT NULL,
  `provider_other_last_name` text,
  `provider_other_first_name` varchar(20) DEFAULT NULL,
  `provider_other_middle_name` varchar(20) DEFAULT NULL,
  `provider_other_name_prefix_text` varchar(5) DEFAULT NULL,
  `provider_other_name_suffix_text` varchar(4) DEFAULT NULL,
  `provider_other_credential_text` varchar(20) DEFAULT NULL,
  `provider_other_last_name_type_code` varchar(1) DEFAULT NULL,
  `provider_first_line_business_mailing_address` text,
  `provider_second_line_business_mailing_address` text,
  `provider_business_mailing_address_city_name` text,
  `provider_business_mailing_address_state_name` text,
  `provider_business_mailing_address_postal_code` varchar(16) DEFAULT NULL,
  `provider_business_mailing_address_country_code` varchar(2) DEFAULT NULL,
  `provider_business_mailing_address_telephone_number` varchar(17) DEFAULT NULL,
  `provider_business_mailing_address_fax_number` varchar(16) DEFAULT NULL,
  `provider_first_line_business_practice_location_address` text,
  `provider_second_line_business_practice_location_address` text,
  `provider_business_practice_location_address_city_name` text,
  `provider_business_practice_location_address_state_name` text,
  `provider_business_practice_location_address_postal_code` varchar(16) DEFAULT NULL,
  `provider_business_practice_location_address_country_code` varchar(2) DEFAULT NULL,
  `provider_business_practice_location_address_telephone_number` varchar(17) DEFAULT NULL,
  `provider_business_practice_location_address_fax_number` varchar(20) DEFAULT NULL,
  `provider_enumeration_date` varchar(10) DEFAULT NULL,
  `last_update_date` varchar(10) DEFAULT NULL,
  `npi_deactivation_date` varchar(10) DEFAULT NULL,
  `npi_reactivation_date` varchar(10) DEFAULT NULL,
  `provider_sex_code` varchar(1) DEFAULT NULL,
  `authorized_official_last_name` text,
  `authorized_official_first_name` varchar(20) DEFAULT NULL,
  `authorized_official_middle_name` varchar(20) DEFAULT NULL,
  `authorized_official_title_or_position` text,
  `authorized_official_telephone_number` varchar(20) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_1` varchar(10) DEFAULT NULL,
  `provider_license_number_1` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_1` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_1` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_2` varchar(10) DEFAULT NULL,
  `provider_license_number_2` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_2` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_2` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_3` varchar(10) DEFAULT NULL,
  `provider_license_number_3` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_3` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_3` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_4` varchar(10) DEFAULT NULL,
  `provider_license_number_4` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_4` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_4` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_5` varchar(10) DEFAULT NULL,
  `provider_license_number_5` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_5` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_5` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_6` varchar(10) DEFAULT NULL,
  `provider_license_number_6` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_6` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_6` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_7` varchar(10) DEFAULT NULL,
  `provider_license_number_7` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_7` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_7` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_8` varchar(10) DEFAULT NULL,
  `provider_license_number_8` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_8` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_8` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_9` varchar(10) DEFAULT NULL,
  `provider_license_number_9` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_9` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_9` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_10` varchar(10) DEFAULT NULL,
  `provider_license_number_10` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_10` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_10` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_11` varchar(10) DEFAULT NULL,
  `provider_license_number_11` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_11` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_11` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_12` varchar(10) DEFAULT NULL,
  `provider_license_number_12` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_12` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_12` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_13` varchar(10) DEFAULT NULL,
  `provider_license_number_state_code_13` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_13` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_14` varchar(10) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_14` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_15` varchar(10) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_15` varchar(1) DEFAULT NULL,
  `other_provider_identifier_1` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_1` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_1` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_1` text,
  `other_provider_identifier_2` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_2` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_2` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_2` text,
  `other_provider_identifier_3` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_3` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_3` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_3` text,
  `other_provider_identifier_4` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_4` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_4` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_4` text,
  `other_provider_identifier_5` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_5` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_5` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_5` text,
  `other_provider_identifier_6` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_6` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_6` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_6` text,
  `other_provider_identifier_7` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_7` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_7` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_7` text,
  `other_provider_identifier_8` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_8` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_8` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_8` text,
  `other_provider_identifier_9` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_9` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_9` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_9` text,
  `other_provider_identifier_10` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_10` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_10` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_10` text,
  `other_provider_identifier_11` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_11` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_11` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_11` text,
  `other_provider_identifier_12` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_12` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_12` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_12` text,
  `other_provider_identifier_13` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_13` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_13` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_13` text,
  `other_provider_identifier_14` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_14` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_14` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_14` text,
  `other_provider_identifier_15` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_15` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_15` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_15` text,
  `other_provider_identifier_16` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_16` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_16` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_16` text,
  `other_provider_identifier_17` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_17` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_17` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_17` text,
  `other_provider_identifier_18` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_18` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_18` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_18` text,
  `other_provider_identifier_19` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_19` varchar(2) DEFAULT NULL,
  `is_sole_proprietor` varchar(1) DEFAULT NULL,
  `is_organization_subpart` varchar(1) DEFAULT NULL,
  `parent_organization_lbn` varchar(70) DEFAULT NULL,
  `parent_organization_tin` varchar(9) DEFAULT NULL,
  `authorized_official_name_prefix_text` varchar(5) DEFAULT NULL,
  `authorized_official_name_suffix_text` varchar(4) DEFAULT NULL,
  `authorized_official_credential_text` varchar(20) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_1` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_2` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_3` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_4` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_5` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_6` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_7` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_8` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_9` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_10` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_11` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_12` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_13` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_14` varchar(10) DEFAULT NULL,
  `certification_date` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: npi_data_0
CREATE TABLE `npi_data_0` (
  `npi` bigint DEFAULT NULL,
  `entity_type_code` varchar(1) DEFAULT NULL,
  `employer_identification_number` varchar(9) DEFAULT NULL,
  `provider_organization_name` varchar(100) DEFAULT NULL,
  `provider_last_name` varchar(35) DEFAULT NULL,
  `provider_first_name` varchar(20) DEFAULT NULL,
  `provider_middle_name` varchar(20) DEFAULT NULL,
  `provider_name_prefix_text` varchar(5) DEFAULT NULL,
  `provider_name_suffix_text` varchar(4) DEFAULT NULL,
  `provider_credential_text` varchar(20) DEFAULT NULL,
  `provider_other_organization_name` varchar(9) DEFAULT NULL,
  `provider_other_organization_name_type_code` varchar(1) DEFAULT NULL,
  `provider_other_last_name` varchar(35) DEFAULT NULL,
  `provider_other_first_name` varchar(20) DEFAULT NULL,
  `provider_other_middle_name` varchar(20) DEFAULT NULL,
  `provider_other_name_prefix_text` varchar(5) DEFAULT NULL,
  `provider_other_name_suffix_text` varchar(4) DEFAULT NULL,
  `provider_other_credential_text` varchar(20) DEFAULT NULL,
  `provider_other_last_name_type_code` varchar(1) DEFAULT NULL,
  `provider_first_line_business_mailing_address` text,
  `provider_second_line_business_mailing_address` text,
  `provider_business_mailing_address_city_name` text,
  `provider_business_mailing_address_state_name` text,
  `provider_business_mailing_address_postal_code` varchar(16) DEFAULT NULL,
  `provider_business_mailing_address_country_code` varchar(2) DEFAULT NULL,
  `provider_business_mailing_address_telephone_number` varchar(17) DEFAULT NULL,
  `provider_business_mailing_address_fax_number` varchar(16) DEFAULT NULL,
  `provider_first_line_business_practice_location_address` text,
  `provider_second_line_business_practice_location_address` text,
  `provider_business_practice_location_address_city_name` text,
  `provider_business_practice_location_address_state_name` text,
  `provider_business_practice_location_address_postal_code` varchar(16) DEFAULT NULL,
  `provider_business_practice_location_address_country_code` varchar(2) DEFAULT NULL,
  `provider_business_practice_location_address_telephone_number` varchar(17) DEFAULT NULL,
  `provider_business_practice_location_address_fax_number` varchar(20) DEFAULT NULL,
  `provider_enumeration_date` varchar(10) DEFAULT NULL,
  `last_update_date` varchar(10) DEFAULT NULL,
  `npi_deactivation_date` varchar(10) DEFAULT NULL,
  `npi_reactivation_date` varchar(10) DEFAULT NULL,
  `provider_sex_code` varchar(1) DEFAULT NULL,
  `authorized_official_last_name` text,
  `authorized_official_first_name` varchar(20) DEFAULT NULL,
  `authorized_official_middle_name` varchar(20) DEFAULT NULL,
  `authorized_official_title_or_position` text,
  `authorized_official_telephone_number` varchar(20) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_1` varchar(10) DEFAULT NULL,
  `provider_license_number_1` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_1` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_1` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_2` varchar(10) DEFAULT NULL,
  `provider_license_number_2` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_2` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_2` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_3` varchar(10) DEFAULT NULL,
  `provider_license_number_3` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_3` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_3` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_4` varchar(10) DEFAULT NULL,
  `provider_license_number_4` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_4` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_4` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_5` varchar(10) DEFAULT NULL,
  `provider_license_number_5` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_5` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_5` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_6` varchar(10) DEFAULT NULL,
  `provider_license_number_6` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_6` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_6` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_7` varchar(10) DEFAULT NULL,
  `provider_license_number_7` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_7` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_7` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_8` varchar(10) DEFAULT NULL,
  `provider_license_number_8` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_8` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_8` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_9` varchar(10) DEFAULT NULL,
  `provider_license_number_9` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_9` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_9` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_10` varchar(10) DEFAULT NULL,
  `provider_license_number_10` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_10` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_10` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_11` varchar(10) DEFAULT NULL,
  `provider_license_number_11` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_11` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_11` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_12` varchar(10) DEFAULT NULL,
  `provider_license_number_12` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_12` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_12` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_13` varchar(10) DEFAULT NULL,
  `provider_license_number_state_code_13` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_13` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_14` varchar(10) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_14` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_15` varchar(10) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_15` varchar(1) DEFAULT NULL,
  `other_provider_identifier_1` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_1` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_1` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_1` text,
  `other_provider_identifier_2` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_2` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_2` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_2` text,
  `other_provider_identifier_3` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_3` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_3` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_3` text,
  `other_provider_identifier_4` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_4` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_4` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_4` text,
  `other_provider_identifier_5` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_5` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_5` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_5` text,
  `other_provider_identifier_6` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_6` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_6` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_6` text,
  `other_provider_identifier_7` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_7` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_7` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_7` text,
  `other_provider_identifier_8` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_8` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_8` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_8` text,
  `other_provider_identifier_9` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_9` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_9` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_9` text,
  `other_provider_identifier_10` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_10` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_10` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_10` text,
  `other_provider_identifier_11` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_11` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_11` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_11` text,
  `other_provider_identifier_12` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_12` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_12` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_12` text,
  `other_provider_identifier_13` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_13` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_13` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_13` text,
  `other_provider_identifier_14` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_14` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_14` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_14` text,
  `other_provider_identifier_15` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_15` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_15` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_15` text,
  `other_provider_identifier_16` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_16` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_16` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_16` text,
  `other_provider_identifier_17` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_17` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_17` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_17` text,
  `other_provider_identifier_18` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_18` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_18` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_18` text,
  `other_provider_identifier_19` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_19` varchar(2) DEFAULT NULL,
  `is_sole_proprietor` varchar(1) DEFAULT NULL,
  `is_organization_subpart` varchar(1) DEFAULT NULL,
  `parent_organization_lbn` varchar(70) DEFAULT NULL,
  `parent_organization_tin` varchar(9) DEFAULT NULL,
  `authorized_official_name_prefix_text` varchar(5) DEFAULT NULL,
  `authorized_official_name_suffix_text` varchar(4) DEFAULT NULL,
  `authorized_official_credential_text` varchar(20) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_1` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_2` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_3` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_4` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_5` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_6` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_7` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_8` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_9` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_10` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_11` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_12` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_13` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_14` varchar(10) DEFAULT NULL,
  `certification_date` varchar(10) DEFAULT NULL,
  `mail_zip` varchar(5) GENERATED ALWAYS AS (left(`provider_business_mailing_address_postal_code`,5)) STORED,
  `location_zip` varchar(5) GENERATED ALWAYS AS (left(`provider_business_practice_location_address_postal_code`,5)) STORED,
  KEY `npi` (`npi`),
  KEY `mail_zip` (`mail_zip`),
  KEY `location_zip` (`location_zip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: npi_data_1
CREATE TABLE `npi_data_1` (
  `npi` bigint DEFAULT NULL,
  `entity_type_code` varchar(1) DEFAULT NULL,
  `employer_identification_number` varchar(9) DEFAULT NULL,
  `provider_organization_name` varchar(100) DEFAULT NULL,
  `provider_last_name` varchar(35) DEFAULT NULL,
  `provider_first_name` varchar(20) DEFAULT NULL,
  `provider_middle_name` varchar(20) DEFAULT NULL,
  `provider_name_prefix_text` varchar(5) DEFAULT NULL,
  `provider_name_suffix_text` varchar(4) DEFAULT NULL,
  `provider_credential_text` varchar(20) DEFAULT NULL,
  `provider_other_organization_name` varchar(9) DEFAULT NULL,
  `provider_other_organization_name_type_code` varchar(1) DEFAULT NULL,
  `provider_other_last_name` varchar(35) DEFAULT NULL,
  `provider_other_first_name` varchar(20) DEFAULT NULL,
  `provider_other_middle_name` varchar(20) DEFAULT NULL,
  `provider_other_name_prefix_text` varchar(5) DEFAULT NULL,
  `provider_other_name_suffix_text` varchar(4) DEFAULT NULL,
  `provider_other_credential_text` varchar(20) DEFAULT NULL,
  `provider_other_last_name_type_code` varchar(1) DEFAULT NULL,
  `provider_first_line_business_mailing_address` text,
  `provider_second_line_business_mailing_address` text,
  `provider_business_mailing_address_city_name` text,
  `provider_business_mailing_address_state_name` text,
  `provider_business_mailing_address_postal_code` varchar(16) DEFAULT NULL,
  `provider_business_mailing_address_country_code` varchar(2) DEFAULT NULL,
  `provider_business_mailing_address_telephone_number` varchar(17) DEFAULT NULL,
  `provider_business_mailing_address_fax_number` varchar(16) DEFAULT NULL,
  `provider_first_line_business_practice_location_address` text,
  `provider_second_line_business_practice_location_address` text,
  `provider_business_practice_location_address_city_name` text,
  `provider_business_practice_location_address_state_name` text,
  `provider_business_practice_location_address_postal_code` varchar(16) DEFAULT NULL,
  `provider_business_practice_location_address_country_code` varchar(2) DEFAULT NULL,
  `provider_business_practice_location_address_telephone_number` varchar(17) DEFAULT NULL,
  `provider_business_practice_location_address_fax_number` varchar(20) DEFAULT NULL,
  `provider_enumeration_date` varchar(10) DEFAULT NULL,
  `last_update_date` varchar(10) DEFAULT NULL,
  `npi_deactivation_date` varchar(10) DEFAULT NULL,
  `npi_reactivation_date` varchar(10) DEFAULT NULL,
  `provider_sex_code` varchar(1) DEFAULT NULL,
  `authorized_official_last_name` text,
  `authorized_official_first_name` varchar(20) DEFAULT NULL,
  `authorized_official_middle_name` varchar(20) DEFAULT NULL,
  `authorized_official_title_or_position` text,
  `authorized_official_telephone_number` varchar(20) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_1` varchar(10) DEFAULT NULL,
  `provider_license_number_1` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_1` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_1` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_2` varchar(10) DEFAULT NULL,
  `provider_license_number_2` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_2` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_2` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_3` varchar(10) DEFAULT NULL,
  `provider_license_number_3` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_3` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_3` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_4` varchar(10) DEFAULT NULL,
  `provider_license_number_4` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_4` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_4` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_5` varchar(10) DEFAULT NULL,
  `provider_license_number_5` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_5` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_5` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_6` varchar(10) DEFAULT NULL,
  `provider_license_number_6` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_6` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_6` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_7` varchar(10) DEFAULT NULL,
  `provider_license_number_7` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_7` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_7` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_8` varchar(10) DEFAULT NULL,
  `provider_license_number_8` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_8` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_8` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_9` varchar(10) DEFAULT NULL,
  `provider_license_number_9` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_9` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_9` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_10` varchar(10) DEFAULT NULL,
  `provider_license_number_10` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_10` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_10` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_11` varchar(10) DEFAULT NULL,
  `provider_license_number_11` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_11` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_11` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_12` varchar(10) DEFAULT NULL,
  `provider_license_number_12` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_12` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_12` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_13` varchar(10) DEFAULT NULL,
  `provider_license_number_state_code_13` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_13` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_14` varchar(10) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_14` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_15` varchar(10) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_15` varchar(1) DEFAULT NULL,
  `other_provider_identifier_1` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_1` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_1` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_1` text,
  `other_provider_identifier_2` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_2` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_2` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_2` text,
  `other_provider_identifier_3` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_3` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_3` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_3` text,
  `other_provider_identifier_4` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_4` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_4` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_4` text,
  `other_provider_identifier_5` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_5` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_5` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_5` text,
  `other_provider_identifier_6` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_6` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_6` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_6` text,
  `other_provider_identifier_7` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_7` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_7` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_7` text,
  `other_provider_identifier_8` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_8` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_8` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_8` text,
  `other_provider_identifier_9` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_9` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_9` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_9` text,
  `other_provider_identifier_10` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_10` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_10` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_10` text,
  `other_provider_identifier_11` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_11` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_11` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_11` text,
  `other_provider_identifier_12` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_12` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_12` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_12` text,
  `other_provider_identifier_13` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_13` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_13` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_13` text,
  `other_provider_identifier_14` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_14` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_14` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_14` text,
  `other_provider_identifier_15` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_15` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_15` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_15` text,
  `other_provider_identifier_16` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_16` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_16` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_16` text,
  `other_provider_identifier_17` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_17` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_17` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_17` text,
  `other_provider_identifier_18` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_18` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_18` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_18` text,
  `other_provider_identifier_19` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_19` varchar(2) DEFAULT NULL,
  `is_sole_proprietor` varchar(1) DEFAULT NULL,
  `is_organization_subpart` varchar(1) DEFAULT NULL,
  `parent_organization_lbn` varchar(70) DEFAULT NULL,
  `parent_organization_tin` varchar(9) DEFAULT NULL,
  `authorized_official_name_prefix_text` varchar(5) DEFAULT NULL,
  `authorized_official_name_suffix_text` varchar(4) DEFAULT NULL,
  `authorized_official_credential_text` varchar(20) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_1` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_2` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_3` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_4` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_5` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_6` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_7` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_8` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_9` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_10` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_11` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_12` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_13` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_14` varchar(10) DEFAULT NULL,
  `certification_date` varchar(10) DEFAULT NULL,
  `mail_zip` varchar(5) GENERATED ALWAYS AS (left(`provider_business_mailing_address_postal_code`,5)) STORED,
  KEY `npi` (`npi`),
  KEY `idx_last_name` (`provider_last_name`),
  KEY `idx_organization_name` (`provider_organization_name`),
  KEY `idx_other_last_name` (`provider_other_last_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: npi_data_2
CREATE TABLE `npi_data_2` (
  `npi` bigint DEFAULT NULL,
  `entity_type_code` varchar(1) DEFAULT NULL,
  `employer_identification_number` varchar(9) DEFAULT NULL,
  `provider_organization_name` varchar(100) DEFAULT NULL,
  `provider_last_name` varchar(35) DEFAULT NULL,
  `provider_first_name` varchar(20) DEFAULT NULL,
  `provider_middle_name` varchar(20) DEFAULT NULL,
  `provider_name_prefix_text` varchar(5) DEFAULT NULL,
  `provider_name_suffix_text` varchar(4) DEFAULT NULL,
  `provider_credential_text` varchar(20) DEFAULT NULL,
  `provider_other_organization_name` varchar(9) DEFAULT NULL,
  `provider_other_organization_name_type_code` varchar(1) DEFAULT NULL,
  `provider_other_last_name` varchar(35) DEFAULT NULL,
  `provider_other_first_name` varchar(20) DEFAULT NULL,
  `provider_other_middle_name` varchar(20) DEFAULT NULL,
  `provider_other_name_prefix_text` varchar(5) DEFAULT NULL,
  `provider_other_name_suffix_text` varchar(4) DEFAULT NULL,
  `provider_other_credential_text` varchar(20) DEFAULT NULL,
  `provider_other_last_name_type_code` varchar(1) DEFAULT NULL,
  `provider_first_line_business_mailing_address` text,
  `provider_second_line_business_mailing_address` text,
  `provider_business_mailing_address_city_name` text,
  `provider_business_mailing_address_state_name` text,
  `provider_business_mailing_address_postal_code` varchar(16) DEFAULT NULL,
  `provider_business_mailing_address_country_code` varchar(2) DEFAULT NULL,
  `provider_business_mailing_address_telephone_number` varchar(17) DEFAULT NULL,
  `provider_business_mailing_address_fax_number` varchar(16) DEFAULT NULL,
  `provider_first_line_business_practice_location_address` text,
  `provider_second_line_business_practice_location_address` text,
  `provider_business_practice_location_address_city_name` text,
  `provider_business_practice_location_address_state_name` text,
  `provider_business_practice_location_address_postal_code` varchar(16) DEFAULT NULL,
  `provider_business_practice_location_address_country_code` varchar(2) DEFAULT NULL,
  `provider_business_practice_location_address_telephone_number` varchar(17) DEFAULT NULL,
  `provider_business_practice_location_address_fax_number` varchar(20) DEFAULT NULL,
  `provider_enumeration_date` varchar(10) DEFAULT NULL,
  `last_update_date` varchar(10) DEFAULT NULL,
  `npi_deactivation_date` varchar(10) DEFAULT NULL,
  `npi_reactivation_date` varchar(10) DEFAULT NULL,
  `provider_sex_code` varchar(1) DEFAULT NULL,
  `authorized_official_last_name` text,
  `authorized_official_first_name` varchar(20) DEFAULT NULL,
  `authorized_official_middle_name` varchar(20) DEFAULT NULL,
  `authorized_official_title_or_position` text,
  `authorized_official_telephone_number` varchar(20) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_1` varchar(10) DEFAULT NULL,
  `provider_license_number_1` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_1` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_1` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_2` varchar(10) DEFAULT NULL,
  `provider_license_number_2` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_2` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_2` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_3` varchar(10) DEFAULT NULL,
  `provider_license_number_3` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_3` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_3` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_4` varchar(10) DEFAULT NULL,
  `provider_license_number_4` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_4` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_4` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_5` varchar(10) DEFAULT NULL,
  `provider_license_number_5` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_5` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_5` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_6` varchar(10) DEFAULT NULL,
  `provider_license_number_6` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_6` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_6` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_7` varchar(10) DEFAULT NULL,
  `provider_license_number_7` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_7` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_7` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_8` varchar(10) DEFAULT NULL,
  `provider_license_number_8` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_8` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_8` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_9` varchar(10) DEFAULT NULL,
  `provider_license_number_9` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_9` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_9` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_10` varchar(10) DEFAULT NULL,
  `provider_license_number_10` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_10` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_10` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_11` varchar(10) DEFAULT NULL,
  `provider_license_number_11` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_11` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_11` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_12` varchar(10) DEFAULT NULL,
  `provider_license_number_12` varchar(20) DEFAULT NULL,
  `provider_license_number_state_code_12` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_12` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_13` varchar(10) DEFAULT NULL,
  `provider_license_number_state_code_13` varchar(2) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_13` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_14` varchar(10) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_14` varchar(1) DEFAULT NULL,
  `healthcare_provider_taxonomy_code_15` varchar(10) DEFAULT NULL,
  `healthcare_provider_primary_taxonomy_switch_15` varchar(1) DEFAULT NULL,
  `other_provider_identifier_1` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_1` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_1` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_1` text,
  `other_provider_identifier_2` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_2` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_2` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_2` text,
  `other_provider_identifier_3` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_3` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_3` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_3` text,
  `other_provider_identifier_4` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_4` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_4` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_4` text,
  `other_provider_identifier_5` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_5` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_5` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_5` text,
  `other_provider_identifier_6` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_6` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_6` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_6` text,
  `other_provider_identifier_7` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_7` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_7` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_7` text,
  `other_provider_identifier_8` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_8` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_8` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_8` text,
  `other_provider_identifier_9` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_9` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_9` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_9` text,
  `other_provider_identifier_10` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_10` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_10` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_10` text,
  `other_provider_identifier_11` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_11` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_11` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_11` text,
  `other_provider_identifier_12` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_12` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_12` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_12` text,
  `other_provider_identifier_13` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_13` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_13` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_13` text,
  `other_provider_identifier_14` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_14` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_14` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_14` text,
  `other_provider_identifier_15` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_15` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_15` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_15` text,
  `other_provider_identifier_16` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_16` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_16` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_16` text,
  `other_provider_identifier_17` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_17` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_17` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_17` text,
  `other_provider_identifier_18` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_18` varchar(2) DEFAULT NULL,
  `other_provider_identifier_state_18` varchar(2) DEFAULT NULL,
  `other_provider_identifier_issuer_18` text,
  `other_provider_identifier_19` varchar(20) DEFAULT NULL,
  `other_provider_identifier_type_code_19` varchar(2) DEFAULT NULL,
  `is_sole_proprietor` varchar(1) DEFAULT NULL,
  `is_organization_subpart` varchar(1) DEFAULT NULL,
  `parent_organization_lbn` varchar(70) DEFAULT NULL,
  `parent_organization_tin` varchar(9) DEFAULT NULL,
  `authorized_official_name_prefix_text` varchar(5) DEFAULT NULL,
  `authorized_official_name_suffix_text` varchar(4) DEFAULT NULL,
  `authorized_official_credential_text` varchar(20) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_1` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_2` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_3` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_4` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_5` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_6` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_7` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_8` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_9` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_10` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_11` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_12` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_13` varchar(10) DEFAULT NULL,
  `healthcare_provider_taxonomy_group_14` varchar(10) DEFAULT NULL,
  `certification_date` varchar(10) DEFAULT NULL,
  `mail_zip` varchar(5) GENERATED ALWAYS AS (left(`provider_business_mailing_address_postal_code`,5)) STORED,
  `location_zip` varchar(5) GENERATED ALWAYS AS (left(`provider_business_practice_location_address_postal_code`,5)) STORED,
  KEY `npi` (`npi`),
  KEY `mail_zip` (`mail_zip`),
  KEY `location_zip` (`location_zip`),
  KEY `idx_last_name` (`provider_last_name`),
  KEY `idx_organization_name` (`provider_organization_name`),
  KEY `idx_other_last_name` (`provider_other_last_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: npi_zips2
CREATE TABLE `npi_zips2` (
  `mail_zip` varchar(5) DEFAULT NULL,
  `recs` bigint NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: procedure_codes
CREATE TABLE `procedure_codes` (
  `procedure_code` varchar(10) NOT NULL,
  `procedure_desc` varchar(1000) DEFAULT NULL,
  `code_category` varchar(20) DEFAULT NULL,
  `code_status` varchar(20) DEFAULT NULL,
  `code_pay_amount` decimal(10,2) DEFAULT '0.00',
  `tier` int unsigned DEFAULT '1',
  KEY `idx_procedure_code` (`procedure_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: procedure_codes_tier1
CREATE TABLE `procedure_codes_tier1` (
  `procedure_code` varchar(10) NOT NULL,
  `procedure_desc` varchar(1000) DEFAULT NULL,
  `code_category` varchar(20) DEFAULT NULL,
  `code_status` varchar(20) DEFAULT NULL,
  `code_pay_amount` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`procedure_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: procedure_codes_tier2
CREATE TABLE `procedure_codes_tier2` (
  `procedure_code` varchar(10) NOT NULL,
  `procedure_desc` varchar(1000) DEFAULT NULL,
  `code_category` varchar(20) DEFAULT NULL,
  `code_status` varchar(20) DEFAULT NULL,
  `code_pay_amount` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`procedure_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: procedure_codes_tier3
CREATE TABLE `procedure_codes_tier3` (
  `procedure_code` varchar(10) NOT NULL,
  `procedure_desc` varchar(1000) DEFAULT NULL,
  `code_category` varchar(20) DEFAULT NULL,
  `code_status` varchar(20) DEFAULT NULL,
  `code_pay_amount` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`procedure_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: procedure_codes_tier4
CREATE TABLE `procedure_codes_tier4` (
  `procedure_code` varchar(10) NOT NULL,
  `procedure_desc` varchar(1000) DEFAULT NULL,
  `code_category` varchar(20) DEFAULT NULL,
  `code_status` varchar(20) DEFAULT NULL,
  `code_pay_amount` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`procedure_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: procedure_codes_tier5
CREATE TABLE `procedure_codes_tier5` (
  `procedure_code` varchar(10) NOT NULL,
  `procedure_desc` varchar(1000) DEFAULT NULL,
  `code_category` varchar(20) DEFAULT NULL,
  `code_status` varchar(20) DEFAULT NULL,
  `code_pay_amount` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`procedure_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: procedure_codes_tiers
CREATE TABLE `procedure_codes_tiers` (
  `procedure_code` varchar(10) NOT NULL,
  `procedure_desc` varchar(1000) DEFAULT NULL,
  `code_category` varchar(20) DEFAULT NULL,
  `code_status` varchar(20) DEFAULT NULL,
  `code_pay_amount` decimal(10,2) DEFAULT '0.00',
  `tier` int unsigned DEFAULT '1',
  PRIMARY KEY (`procedure_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: request_logs
CREATE TABLE `request_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `timestamp` datetime NOT NULL,
  `user_id` varchar(64) DEFAULT NULL,
  `endpoint` varchar(255) DEFAULT NULL,
  `method` varchar(10) DEFAULT NULL,
  `request_payload` text,
  `query_params` text,
  `response_status` int DEFAULT NULL,
  `response_payload` text,
  `execution_time_ms` int DEFAULT NULL,
  `error_message` text,
  `client_ip` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: state_mail_data_2
CREATE TABLE `state_mail_data_2` (
  `provider_business_mailing_address_state_name` text,
  `recs` bigint NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: surgeon_list
CREATE TABLE `surgeon_list` (
  `surgeon_id` int NOT NULL AUTO_INCREMENT,
  `user_id` varchar(100) DEFAULT NULL,
  `first_name` varchar(250) DEFAULT NULL,
  `last_name` varchar(250) DEFAULT NULL,
  `surgeon_npi` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`surgeon_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=100030 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: user_documents
CREATE TABLE `user_documents` (
  `user_id` varchar(100) DEFAULT NULL,
  `document_type` varchar(100) DEFAULT NULL,
  `document_name` varchar(250) DEFAULT NULL,
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: user_groups
CREATE TABLE `user_groups` (
  `user_id` varchar(100) DEFAULT NULL,
  `group_id` int DEFAULT NULL,
  `group_admin` binary(1) DEFAULT NULL,
  KEY `user_id` (`user_id`),
  KEY `group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: user_profile
CREATE TABLE `user_profile` (
  `user_id` varchar(100) NOT NULL,
  `user_email` varchar(250) NOT NULL,
  `first_name` varchar(250) DEFAULT NULL,
  `last_name` varchar(250) DEFAULT NULL,
  `addr1` varchar(250) DEFAULT NULL,
  `addr2` varchar(250) DEFAULT NULL,
  `city` varchar(250) DEFAULT NULL,
  `state` varchar(250) DEFAULT NULL,
  `zipcode` varchar(250) DEFAULT NULL,
  `telephone` bigint unsigned DEFAULT NULL,
  `user_npi` bigint unsigned DEFAULT NULL COMMENT 'National Provider Identification',
  `referred_by_user` varchar(100) DEFAULT NULL,
  `user_type` int unsigned DEFAULT '1' COMMENT '1 = Provider, 2 = Group Admin, 10 = Case Admin, 20 = User Admin, 100 = Global Admin, 999 = System Admin',
  `message_pref` smallint DEFAULT '0' COMMENT '0 = no messages, 1 = email, 2 = sms, 3 = both',
  `create_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login_dt` datetime DEFAULT NULL,
  `active` tinyint DEFAULT '1',
  `states_licensed` varchar(500) DEFAULT NULL,
  `last_updated_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_tier` int unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`user_id`),
  KEY `idx_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

